server:
  port: 8802
spring:
  application:
    name: easy-cloud-account-service
  profiles:
    active: dev


mybatis-plus:
  type-aliases-package: com.hu4java.cloud.accout.entity
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    banner: false